version: 0.2

phases:
  install:
    commands:
      # Skip installing Apache, PHP, and WordPress since it's already in the AMI
      - echo "Skipping installation of dependencies as they are already pre-configured in the AMI."

  pre_build:
    # Any pre-build tasks you may need, like environment variable setup
    commands:
      - echo "Running pre-build steps"

  build:
    # Build process (e.g., copying custom themes, plugins, or configurations)
    commands:
      - echo "Starting WordPress deployment..."
      - echo "WordPress files deployed successfully."

  post_build:
    # Post-build actions (e.g., configuring wp-config.php or setting up database)
    commands:
      - echo "Configuring wp-config.php..."
      # Restart Apache web server
      - echo "Restarting Apache web server..."
      - sudo systemctl restart apache2

artifacts:
  files:
    - wp-config.php       # Include the wp-config.php if modified
    - '**/*'              # Include all other files for deployment

cache:
  paths:
    - /tmp/*
